Changed the java compiler level from 1.7 to 1.6, that way if you haven't updated to 1.7 you should be ok. If you get a NoClassDefFoundError when trying to run the application make sure your jre and javac is updated to version 1.6